export const sectionsList = {
    artanddesign: "Art and design",
    business: "Business",
    culture: "Culture",
    education: "Education",
    environment: "Environment",
    fashion: "Fashion",
    film: "Film",
    food: "Food",
    football: "Football",
    games: "Games",
    inequality: "Inequality",
    law: "Law",
    lifeandstyle: "Life and style",
    media: "Media",
    money: "Money",
    music: "Music",
    politics: "Politics",
    science: "Science",
    society: "Society",
    sport: "Sport",
    technology: "Technology",
    travel: "Travel",
    weather: "Weather",
    world: "World news",
};
export const searchNewsApi = "https://content.guardianapis.com/search?&api-key=7494be0e-6ed6-486e-b2ac-f84307bee564&page-size=12&show-fields=headline,thumbnail,trailText,lastModified";
